import { isDenied, repoById } from "./allowlist";
import type { AllowlistedRepo, PolicyVerdict } from "./types";

const FORBIDDEN_PHRASES = [
  "autonomous agents not allowed",
  "autonomous agent",
  "no ai generated pr",
  "no ai-generated",
  "ai slop",
  "slop prs not welcome",
  "bots are not welcome",
  "do not submit ai",
  "llm generated contributions are not accepted",
  "generated by copilot not accepted",
];

const HUMAN_PHRASES = [
  "human:",
  "human required",
  "must be reviewed by a human",
  "human attest",
  "dco",
  "developer certificate of origin",
  "sign the cla",
  "cla required",
  "contributor license agreement",
];

export function scanPolicyText(text: string): {
  forbidden: string[];
  human: string[];
} {
  const lower = text.toLowerCase();
  return {
    forbidden: FORBIDDEN_PHRASES.filter((p) => lower.includes(p)),
    human: HUMAN_PHRASES.filter((p) => lower.includes(p)),
  };
}

export function evaluatePolicy(input: {
  repoId: string;
  agentsMd?: string;
  contributing?: string;
  issueTitle?: string;
  filesHint?: number;
  diffHint?: number;
}): PolicyVerdict {
  const denied = isDenied(input.repoId);
  if (denied) {
    return {
      allow: false,
      code: "DENY_FORBIDDEN",
      reasons: [denied.reason],
      matchedPhrases: [],
    };
  }

  const repo = repoById(input.repoId);
  if (!repo) {
    return {
      allow: false,
      code: "DENY_UNKNOWN_POLICY",
      reasons: [`${input.repoId} is not on the allowlist.`],
      matchedPhrases: [],
    };
  }

  const blob = `${input.agentsMd ?? ""}\n${input.contributing ?? ""}\n${repo.policyNotes}`;
  const scanned = scanPolicyText(blob);

  if (scanned.forbidden.length > 0 || repo.aiPolicy === "forbidden") {
    return {
      allow: false,
      code: "DENY_FORBIDDEN",
      reasons: ["Repo policy forbids autonomous or AI-generated PRs."],
      matchedPhrases: scanned.forbidden,
    };
  }

  if (repo.aiPolicy === "unknown" && !input.agentsMd && !input.contributing) {
    return {
      allow: false,
      code: "DENY_UNKNOWN_POLICY",
      reasons: [
        "AI policy is unknown. Fetch AGENTS.md / CONTRIBUTING and re-run the gate before freeze.",
      ],
      matchedPhrases: [],
    };
  }

  const reasons: string[] = [];
  const matched = [...scanned.human];

  if (repo.aiPolicy === "human-required" || scanned.human.length > 0) {
    const cla = scanned.human.some(
      (p) => p.includes("cla") || p.includes("dco") || p.includes("certificate"),
    );
    return {
      allow: false,
      code: cla ? "HOLD_CLA" : "HOLD_HUMAN",
      reasons: [
        cla
          ? "CLA/DCO requires a human signature. Park needs-human. Never forge."
          : "Policy requires a human attest before any PR is opened.",
      ],
      matchedPhrases: matched,
    };
  }

  if (typeof input.filesHint === "number" && input.filesHint > repo.maxFiles) {
    return {
      allow: false,
      code: "HOLD_SCOPE",
      reasons: [`Packet would touch ${input.filesHint} files; cap is ${repo.maxFiles}.`],
      matchedPhrases: [],
    };
  }

  if (typeof input.diffHint === "number" && input.diffHint > repo.maxDiffLines) {
    return {
      allow: false,
      code: "HOLD_SCOPE",
      reasons: [`Diff ${input.diffHint} lines exceeds cap ${repo.maxDiffLines}.`],
      matchedPhrases: [],
    };
  }

  if (/rfc|tracking|meta|epic/i.test(input.issueTitle ?? "")) {
    return {
      allow: false,
      code: "HOLD_SCOPE",
      reasons: ["Issue looks like RFC/meta/tracking — out of scope for the factory."],
      matchedPhrases: [],
    };
  }

  reasons.push("Allowlisted, policy parsed, scope inside caps.");
  return { allow: true, code: "ALLOW", reasons, matchedPhrases: matched };
}

export function policyLabel(code: PolicyVerdict["code"]): string {
  switch (code) {
    case "ALLOW":
      return "Allow";
    case "DENY_FORBIDDEN":
      return "Denied · forbidden";
    case "DENY_UNKNOWN_POLICY":
      return "Denied · unknown policy";
    case "HOLD_CLA":
      return "Hold · CLA/DCO";
    case "HOLD_HUMAN":
      return "Hold · human";
    case "HOLD_SCOPE":
      return "Hold · scope";
  }
}

export function demoPolicyCorpus(repo: AllowlistedRepo): string {
  if (repo.aiPolicy === "owner") {
    return "# AGENTS.md\n\nThis is our repository. Agents may open draft PRs. Human freeze still applies to Wave 0 for the first 20 packets.\n";
  }
  if (repo.aiPolicy === "welcome") {
    return "# CONTRIBUTING\n\nWell-formed agent PRs are welcome if they include tests, a failing-first reproduction, and a short disclosure. Keep diffs small.\n";
  }
  if (repo.aiPolicy === "human-required") {
    return "# CONTRIBUTING\n\nHUMAN: required on every PR. Sign the DCO. Autonomous merges are not permitted.\n";
  }
  return "";
}
